#!/bin/bash

set -euo pipefail

IMAGE_NAME="silhouette:latest"
CONTAINER_NAME="silhouette-dev"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

docker build --pull --no-cache -f "${REPO_ROOT}/Dockerfile" -t "${IMAGE_NAME}" "${REPO_ROOT}"

docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1 || true

docker run -d --rm --name "${CONTAINER_NAME}" -p "${SILHOUETTE_SERVICE_PORT: -4}":"${SILHOUETTE_SERVICE_PORT: -4}" \
    -e SILHOUETTE_SERVICE_CLIENT_ID \
    -e SILHOUETTE_SERVICE_PORT \
    -e SILHOUETTE_CA_CERT \
    -e SILHOUETTE_SERVER_CERT \
    -e SILHOUETTE_SERVER_KEY \
    -e SILHOUETTE_DB_CA_CERT \
    -e SILHOUETTE_DB_CLIENT_CERT \
    -e SILHOUETTE_DB_CLIENT_KEY \
    -e SILHOUETTE_DATABASE_URL \
    -e SILHOUETTE_DATABASE_NAME \
    -e SILHOUETTE_DATABASE_USERNAME \
    -e SILHOUETTE_DATABASE_PASSWORD \
    -e SILHOUETTE_DATABASE_HMAC_INDEX_SECRET \
    -e SILHOUETTE_FIELD_LEVEL_AES_GCM_SECRET \
    -e SILHOUETTE_S2S_JWT_VERIFYING_KEY \
    -e SILHOUETTE_USER_JWT_VERIFYING_KEY \
    "${IMAGE_NAME}"
